language: node_js
node_js:
  - '4.1'

deploy:
  provider: heroku
  api_key:
    secure: F8DNx8YSTy50mtmMRhIb2/G3wuyAFmawwbiJqfy+nz8xiOSO/R2Ibs/UfSh1snrxQzRxiepJ5Qv7QLMDmNRGv1MBv11LAjEC/jwuyOu5tiM4nnp4xPzj+J+8qNVHTsAp15G8H06cHmg0Gu3MZN3wgrYEhxdJTXGiECsHX+rI3qxSClrFHxeUbTIu6HoNDCZjKGUSs4hs5wtAoU6AvjboPccmkrrW3DoPaLbmHcAzXnTKi0UrJxwP3dWzxBX8WZxmPtIrhQk9APoj0TOTkosKoL+gqbWD7SXFgzxhK/MoqoO6gp9N30OoXbTdV3XDFCk3XdP1UXNOgLSBI6+ROTy1c9VisUNKPPFhI5QKiBu/RjvizVbJjSYIhUsLX6nC18Yzry4NtckdUcR39pDNZlby69gGYA+K4ljjMsn3xKT227h7u2y5NpCraL95DsCOnSoLCZedcmjtYkCq6tL1571fuLcJKh5CJZceb8AdJc9VRA3QT81fI3mjiBG7XQL04D8y1Xw9qBPtl+6UOFLAJWRK+Ix3YFxZUNQ2gHYZRdkA1gk7wj/KODhyW/w5HQttBKKm/lMfCLOukaa+FeeCQA8iclLbt3dICgpIkzgVt/Xi3KHP9qhZGQhCETaFEvjQtqyavPF1QU44zlExg4h6mNCdkfajjyb+1snfcvwT1QGBYs4=
